-- colorscheme autogenerated with base16
vim.cmd "source ~/.config/nvim/vim_colors/default.vim"

-- main
require('core')
require('options')
require('keymaps')

-- plugins and settings
require('plugins')
require('pluginconf.nvim-autopairs')
require('pluginconf.alphaconf')
require('pluginconf.bufferline')
require('pluginconf.latex')
require('pluginconf.lspsaga')
require('pluginconf.luasnip')
require('pluginconf.telescope')
require('pluginconf.treesitter')
require('pluginconf.autoformat')
require('pluginconf.cmp')
require('pluginconf.lsp')
require('pluginconf.lualine')
require('pluginconf.nvim-tree')
require('pluginconf.toggleterm')
require('pluginconf.null-ls')

-- sourcing color scheme adjustments
require('colors')

-- needs fixing
require('Comment').setup()
