#!/bin/bash
while test $# -gt 0; do
  case "$1" in
    -h|--help)
      echo "There should be a title.docx in parent folder"
      echo "usage:"
      echo ""
      echo "compd myfile.md"
      exit 0
      ;;
    *)
      break
      ;;
  esac
done

title="../title.docx"

[ -n "$1" ] && filename=$(echo "$1" | rev | cut -c 4- | rev)
#[ -n "$1" ] || [ -n "$2" ] || echo "You need to pass 2 arguments!" && exit 0
if [ -n "$1" ]; then
#  pandoc $1 -o lab2.docx
  if [ -n "$2" ]; then
    title=$(echo $2)
  fi

[ -f "$title" ] || exit 0

pandoc $1 -o $filename.docx
docxcompose $title $filename.docx -o $filename.docx

echo "done!"
fi
