font:
  # Normal (roman) font face
  normal:
    family: Hack Nerd Font Mono
    style: Regular

  # Bold font face
  bold:
    family: Hack Nerd Font Mono
    style: Bold

  # Italic font face
  italic:
    family: Hack Nerd Font Mono
    style: Italic

  # Bold italic font face
  bold_italic:
    family: Hack Nerd Font Mono
    style: Bold Italic

  # Point size
  size: 11.5

colors:
  # Default colors
  primary:
    # hard contrast: background = '0x1d2021'
    background: '0x282828'
    # soft contrast: background = '0x32302f'
    foreground: '0xebdbb2'

  # Normal colors
  normal:
    #black:   '0x928374'
    black:   '0x282828'
    red:     '0xfb4934'
    green:   '0xb8bb26'
    yellow:  '0xfabd2f'
    blue:    '0x83a598'
    magenta: '0xd3869b'
    cyan:    '0x8ec07c'
    white:   '0xebdbb2'

  # Bright colors
  bright:
    #black:   '0x928374'
    black:   '0x282828'
    red:     '0xfb4934'
    green:   '0xb8bb26'
    yellow:  '0xfe8019'
    blue:    '0x83a598'
    magenta: '0xd3869b'
    cyan:    '0x8ec07c'
    white:   '0xebdbb2'
# Start flavours
# Base16 OneDark - alacritty color config
# Lalit Magant (http://github.com/tilal6991)
colors:
  # Default colors
  primary:
    background: '0x282c34'
    foreground: '0xabb2bf'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x282c34'
    cursor: '0xabb2bf'

  # Normal colors
  normal:
    black:   '0x282c34'
    red:     '0xe06c75'
    green:   '0x98c379'
    yellow:  '0xe5c07b'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0xabb2bf'

  # Bright colors
  bright:
    black:   '0x545862'
    red:     '0xd19a66'
    green:   '0x353b45'
    yellow:  '0x3e4451'
    blue:    '0x565c64'
    magenta: '0xb6bdca'
    cyan:    '0xbe5046'
    white:   '0xc8ccd4'

draw_bold_text_with_bright_colors: false
# End flavours
