font:
  # Normal (roman) font face
  normal:
    # family: Hack Nerd Font Mono
    family: JetBrainsMono Nerd Font Mono
    style: Regular

  # Bold font face
  bold:
    # family: Hack Nerd Font Mono
    family: JetBrainsMono Nerd Font Mono
    style: Bold

  # Italic font face
  italic:
    # family: Hack Nerd Font Mono
    family: JetBrainsMono Nerd Font Mono
    style: Italic

  # Bold italic font face
  bold_italic:
    # family: Hack Nerd Font Mono
    family: JetBrainsMono Nerd Font Mono
    style: Bold Italic

  # Point size
  size: 11

# Start flavours
# Base16 Tokyonight - alacritty color config
# Folke Lemaitre (https://github.com/folke)
colors:
  # Default colors
  primary:
    background: '0x24283b'
    foreground: '0xc0caf5'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x24283b'
    cursor: '0xc0caf5'

  # Normal colors
  normal:
    black:   '0x24283b'
    red:     '0xf7768e'
    green:   '0x9ece6a'
    yellow:  '0xe0af68'
    blue:    '0x41a6b5'
    magenta: '0xbb9af7'
    cyan:    '0x1abc9c'
    white:   '0xc0caf5'

  # Bright colors
  bright:
    black:   '0x565f89'
    red:     '0xff9e64'
    green:   '0x1f2335'
    yellow:  '0x292e42'
    blue:    '0xa9b1d6'
    magenta: '0xc0caf5'
    cyan:    '0xff007c'
    white:   '0xc0caf5'

draw_bold_text_with_bright_colors: false
# End flavours
window:
  opacity: 0.8
