#!/bin/env bash

#colors
x1="$(xrdb -query | grep 'color1:'| awk '{print $NF}')"
x2="$(xrdb -query | grep 'color9:'| awk '{print $NF}')"
x3="$(xrdb -query | grep 'color2:'| awk '{print $NF}')"
x4="$(xrdb -query | grep 'color10:'| awk '{print $NF}')"
x5="$(xrdb -query | grep 'color3:'| awk '{print $NF}')"
x6="$(xrdb -query | grep 'color11:'| awk '{print $NF}')"
x7="$(xrdb -query | grep 'color4:'| awk '{print $NF}')"
x8="$(xrdb -query | grep 'color12:'| awk '{print $NF}')"
x9="$(xrdb -query | grep 'color5:'| awk '{print $NF}')"
x10="$(xrdb -query | grep 'color13:'| awk '{print $NF}')"
x11="$(xrdb -query | grep 'color6:'| awk '{print $NF}')"
x12="$(xrdb -query | grep 'color14:'| awk '{print $NF}')"

#functions
gradient(){
convert -size "1920x1080" -define gradient:angle="35" gradient:"$1-$2" "$HOME/Wallpapers/gradient.png"
feh --bg-fill $HOME/Wallpapers/gradient.png
echo "gradient.png" > $HOME/.cache/lastwallpaper
exit
}

apply(){
flavours apply $1
awesome-client 'awesome.restart()'
}

applytelegram(){
killall telegram-desktop
wal-telegram && telegram-desktop $HOME/.cache/wal-telegram/wal.tdesktop-theme &
}

#apply base16
list=$(flavours list)
custom=""
concat=$(echo "$list $custom" | sed 's/\s\+/\n/g')
theme=$(echo "$concat" | rofi -dmenu)
[ ! -z "$theme" ] && apply "$theme"

#apply wallpaper
wallist=$(ls $HOME/Wallpapers)
custom2="default gradient-warm gradient-limy gradient-foggy gradient-strawberry"
concat2=$(echo "$custom2 $wallist" | sed 's/\s\+/\n/g')
wal=$(echo "$concat2" | rofi -dmenu)
[ -z "$wal" ] && exit

echo "$wal" > $HOME/.cache/lastwallpaper

[ "$wal" == "default" ] && exit
[ "$wal" == "gradient-warm" ] && gradient "$x2" "$x5"
[ "$wal" == "gradient-limy" ] && gradient "$x3" "$x7"
[ "$wal" == "gradient-foggy" ] && gradient "$x7" "$x9"
[ "$wal" == "gradient-strawberry" ] && gradient "$x9" "$x2"
feh --bg-fill $HOME/Wallpapers/$wal

#Other
telegrunning=$(pidof telegram-desktop)
waltelegexists=$(command -v wal-telegram)
[ -z $telegrunning ] && [ -z $waltelegexists ] || applytelegram
