#!/bin/sh


rofifunc()
{
	rfile=$(ls $HOME/Soundboard | rofi -dmenu)
	if [ $rfile = "stop" ]; then
		killmpv
		exit
	fi

	if [[ ! -f $HOME/Soundboard/$rfile ]]; then
		exit
	fi
	
	volume=$(printf '40\n100\n20\n60' | rofi -dmenu)

	mpv --audio-device='pulse/sink_mix' --volume=$volume $HOME/Soundboard/$rfile
}


play(){
	ffile=$HOME/Soundboard/"$1".mp3
	
	if [[ ! -f $HOME/Soundboard/$ffile ]]; then 
		exit
	fi

	mpv --audio-device='pulse/sink_mix' $HOME/Soundboard/$ffile
}

list()
{
	ls $HOME/Soundboard/
}


killmpv()
{
	killall mpv
}

[[ $# -eq 1 ]] && [[ $1 == -r ]] && rofifunc && exit
[[ $# -eq 1 ]] && [[ $1 == -l ]] && list && exit
[[ $# -eq 1 ]] && [[ $1 == -d ]] && download && exit
[[ $# -eq 1 ]] && play "$1"
